import React from "react";
import Provider from "./provider";
import 'bootstrap/dist/css/bootstrap.css';
import TopNavbar from "../components/layout/TopNavbar";
import SessionStatusWrapper from "../components/layout/SessionStatus";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    return (
    <html lang="en" >
      <body className={"w-100"} suppressHydrationWarning={true}>
      <Provider>
          <SessionStatusWrapper>
              <TopNavbar   />

              <div  className="  ps-3 pe-3 w-100 " >

                  {children}

              </div>
          </SessionStatusWrapper>


      </Provider>
      </body>
    </html>
  )
}
